### ISSUE TITLE
Quick question on quickview.js

### ISSUE THREAD

**Issue by ajmalafif** [kellyvaughn/quickview-for-shopify#1]
Hello there!

Thanks so much for sharing this. I believe i managed to implement everything but somehow i keep getting this, “The requested content cannot be loaded. Please try again later” when clicking `Quick View`.

I've noticed things like https://github.com/mbhattilc/quickview-for-shopify/blob/master/quickview.js.liquid#L9 and changed to my theme's collection's class but i'm missing something somewhere. 

Do you by any chance do minor changes (paid) job? I think i'm close i just don't know what I'm missing.

**Comment by ajmalafif** [comment]
https://chicgoal.myshopify.com/collections/all
pass: chic

To see the example I meant. There's no error so i'm dumbfounded on how to fix it T_T

**Comment by kellyvaughn** [comment]
Hey @ajmalafif! Feel free to shoot me an email about this - kelly@kellyvaughncreative.com

**Comment by ajmalafif** [comment]
@kellyvaughn Email sent!
